apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    application: tomcat-demo
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
